language: node_js
node_js:
  - '16'
cache:
  directories:
    - node_modules
script:
  - CI=false npm run build

# after_success:
#   - npm run coverage

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
